In [51]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

import re  # Import the regular expression module

In [52]:
# Load specific sheets
sheets_to_load = ['Germany',
                  'Italy',
                  'Poland',
                  'Switzerland',
                  'Sweden',
                  'Thailand',
                  'UK',
                  'Vietnam',
                  'Australia']

# selected_sheets = pd.read_excel(r'C:\Users\aisar\Downloads\Raw data files (Sept24)\Compilation-raw\user-profile-compilation-v1.xlsx', sheet_name=sheets_to_load)
# selected_sheets = pd.read_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\Compilation-raw\SEPTEMBER\user-profile-compilation.xlsx', sheet_name=sheets_to_load)
# selected_sheets = pd.read_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\Compilation-raw\OCTOBER\user-profile-compilation.xlsx', sheet_name=sheets_to_load)
# selected_sheets = pd.read_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\Compilation-raw\NOVEMBER\user-profile-compilation.xlsx', sheet_name=sheets_to_load)
selected_sheets = pd.read_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\Compilation-raw\DECEMBER\user-profile-compilation.xlsx', sheet_name=sheets_to_load)

# Access each sheet by its name
Germany = selected_sheets['Germany']
Italy = selected_sheets['Italy']
Poland = selected_sheets['Poland']
Switzerland = selected_sheets['Switzerland']
Sweden = selected_sheets['Sweden']
Thailand = selected_sheets['Thailand']
UK = selected_sheets['UK']
Vietnam = selected_sheets['Vietnam']
Australia = selected_sheets['Australia']

### Special Case - Range household income

In [53]:
# # Rename the column again, using the exact name displayed in the output above
# Germany = Germany.rename(columns={"GM - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Sweden = Sweden.rename(columns={"SW - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Italy = Italy.rename(columns={"IT - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Poland = Poland.rename(columns={"PO - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# UK = UK.rename(columns={"UK - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Australia = Australia.rename(columns={"AU - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Vietnam = Vietnam.rename(columns={"VN - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Switzerland = Switzerland.rename(columns={"SZ - What is your household's total annual gross income before taxes?": 'Range_household_income'})
# Thailand = Thailand.rename(columns={"TH - What is your household's total annual gross income before taxes?": 'Range_household_income'})

### Germany

In [54]:
Germany.columns = Germany.columns.str.strip() # Clean up any extra whitespace in column names
print(Germany.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'GM - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [55]:
# Rename specific columns
Germany = Germany.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "GM - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'GM - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Germany.columns = Germany.columns.str.strip() # Clean up any extra whitespace in column names
print(Germany.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [56]:
# # Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

# # Rename the column again, using the exact name displayed in the output above
# Germany = Germany.rename(columns={
#     'GM - What is your households total annual gross income before taxes?': 'Range_household_income'
# })

Germany.columns = Germany.columns.str.strip() # Strip any extra whitespace from column names just in case
print(Germany.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [57]:
Germany.head()

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78230,25/11/2024 16:40:55,Complete,81.89.172.225,9.4910,51.299301,Germany,NaN,NaN,NaN,...,2,1,1,2,43,4,13,2,1,1
1,78263,25/11/2024 17:32:48,Complete,89.247.204.9,11.5683,48.166302,Germany,Munich,02,80803.0,...,2,1,4,1,28,3,12,2,2,2
2,78268,25/11/2024 17:34:02,Complete,93.202.156.104,10.6804,53.873901,Germany,Lubeck,10,23554.0,...,2,14,4,2,44,4,9,2,1,2
3,78278,25/11/2024 17:34:35,Complete,91.18.245.222,9.1827,48.766998,Germany,Stuttgart,01,70174.0,...,2,2,4,2,50,5,15,2,2,2
4,78299,25/11/2024 17:33:44,Complete,91.11.132.57,13.1934,52.509701,Germany,Berlin,16,13595.0,...,2,12,4,2,39,4,7,3,2,1

In [58]:
# Convert the columns to string
Germany['Gender'] = Germany['Gender'].astype(str)
Germany['highest level of education you have completed?'] = Germany['highest level of education you have completed?'].astype(str)
Germany['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Germany['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)
Germany['Age Range'] = Germany['Age Range'].astype(str)
Germany['Region'] = Germany['Region'].astype(str)
Germany['best applies to the home you live in?'] = Germany['best applies to the home you live in?'].astype(str)
Germany['decision maker'] = Germany['decision maker'].astype(str)


# Rename specific row values

################################################## Fixed ##################################################
Germany['Gender'] = Germany['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Germany['highest level of education you have completed?'] = Germany['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Germany['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Germany['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})


Germany['best applies to the home you live in?'] = Germany['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Germany['Age Range'] = Germany['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Germany['decision maker'] = Germany['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Germany['Region'] = Germany['Region'].replace({
    '1': 'Bayern',
    '2': 'Baden Württemberg',
    '3': 'Hessen',
    '4': 'Rheinland Pfalz',
    '5': 'Saarland',
    '6': 'Sachsen',
    '7': 'Sachsen Anhalt',
    '8': 'Nordrhein Westfalen',
    '9': 'Niedersachsen',
    '10': 'Thüringen',
    '11': 'Brandenburg',
    '12': 'Berlin',
    '13': 'Mecklenburg Vorpommern',
    '14': 'Schleswig Holstein',
    '15': 'Bremen',
    '16': 'Hamburg'
})


Germany['Range_household_income'] = Germany['Range_household_income'].replace({
    '1': 'Up to € 19.999',
    '2': '€ 20.000 - € 22.499',
    '3': '€ 22.500 - € 24.999',
    '4': '€ 25.000 - € 27.499',
    '5': '€ 27.500 - € 29.999',
    '6': '€ 30.000 - € 32.499',
    '7': '€ 32.500 - € 34.999',
    '8': '€ 35.000 - € 37.499',
    '9': '€ 37.500 - € 39.999',
    '10': '€ 40.000 - € 44.999',
    '11': '€ 45.000 - € 49.999',
    '12': '€ 50.000 - € 59.999',
    '13': '€ 60.000 - € 69.999',
    '14': '€ 70.000 - € 80.000',
    '15': '€ 80.000 or more',
    '16': 'Dont know / Prefer not to answer',
    '99': 'Dont know / Prefer not to answer'
})

print(Germany.head())

   Response ID       Date Submitted    Status      IP Address  Longitude  \
0        78230  25/11/2024 16:40:55  Complete   81.89.172.225     9.4910
1        78263  25/11/2024 17:32:48  Complete    89.247.204.9    11.5683
2        78268  25/11/2024 17:34:02  Complete  93.202.156.104    10.6804
3        78278  25/11/2024 17:34:35  Complete   91.18.245.222     9.1827
4        78299  25/11/2024 17:33:44  Complete    91.11.132.57    13.1934

    Latitude  Country       City State/Region   Postal  ...  \
0  51.299301  Germany        NaN          NaN      NaN  ...
1  48.166302  Germany     Munich           02  80803.0  ...
2  53.873901  Germany     Lubeck           10  23554.0  ...
3  48.766998  Germany  Stuttgart           01  70174.0  ...
4  52.509701  Germany     Berlin           16  13595.0  ...

   Which country are you currently residing in?              Region  \
0                                             2              Bayern
1                                             2              Bayern
2                                             2  Schleswig Holstein
3                                             2   Baden Württemberg
4                                             2              Berlin

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                                     Rural/ village                 Female
1                             Urban city/ large town                   Male
2                             Urban city/ large town                 Female
3                             Urban city/ large town                 Female
4                             Urban city/ large town                 Female

  Age  Age Range  Range_household_income  \
0  43      35-44     € 60.000 - € 69.999
1  28      25-34     € 50.000 - € 59.999
2  44      35-44     € 37.500 - € 39.999
3  50      45-60        € 80.000 or more
4  39      35-44     € 32.500 - € 34.999

   highest level of education you have completed?  \
0                     Middle School / High School
1                     Middle School / High School
2                     Middle School / High School
3                     Middle School / High School
4    Diploma / Technical College / Junior College

   best applies to the home you live in?  \
0                               I own it
1                              I rent it
2                               I own it
3                              I rent it
4                              I rent it

                                      decision maker
0  I am solely responsible for choosing the domes...
1  I share responsibility with someone else in th...
2  I share responsibility with someone else in th...
3  I share responsibility with someone else in th...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [59]:
print(Germany['Range_household_income'].value_counts(), "\n")
print(Germany['Region'].value_counts())

Range_household_income
Up to € 19.999                      50
€ 60.000 - € 69.999                 35
€ 80.000 or more                    35
€ 45.000 - € 49.999                 34
€ 50.000 - € 59.999                 30
€ 40.000 - € 44.999                 28
€ 70.000 - € 80.000                 27
€ 20.000 - € 22.499                 26
€ 37.500 - € 39.999                 24
€ 27.500 - € 29.999                 19
€ 32.500 - € 34.999                 17
€ 25.000 - € 27.499                 17
€ 35.000 - € 37.499                 16
€ 30.000 - € 32.499                 16
€ 22.500 - € 24.999                 13
Dont know / Prefer not to answer     9
Name: count, dtype: int64

Region
Nordrhein Westfalen       86
Bayern                    52
Baden Württemberg         45
Niedersachsen             32
Sachsen                   30
Hessen                    25
Berlin                    25
Brandenburg               19
Schleswig Holstein        16
Sachsen Anhalt            15
Rheinland Pfalz           14
Hamburg                   12
Mecklenburg Vorpommern     9
Thüringen                  8
Bremen                     4
Saarland                   4
Name: count, dtype: int64

In [60]:
Germany.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78230,25/11/2024 16:40:55,Complete,81.89.172.225,9.4910,51.299301,Germany,NaN,NaN,NaN,...,2,Bayern,Rural/ village,Female,43,35-44,€ 60.000 - € 69.999,Middle School / High School,I own it,I am solely responsible for choosing the domes...
1,78263,25/11/2024 17:32:48,Complete,89.247.204.9,11.5683,48.166302,Germany,Munich,02,80803.0,...,2,Bayern,Urban city/ large town,Male,28,25-34,€ 50.000 - € 59.999,Middle School / High School,I rent it,I share responsibility with someone else in th...

### Sweden

In [61]:
Sweden.columns = Sweden.columns.str.strip() # Clean up any extra whitespace in column names
print(Sweden.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'SW - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [62]:
# Rename specific columns
Sweden = Sweden.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'SW - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Sweden.columns = Sweden.columns.str.strip() # Clean up any extra whitespace in column names
print(Sweden.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [63]:
# # Display all columns to identify any extra spaces or unusual characters
# for col in Sweden.columns:
#     print(f"'{col}'")

# # Rename the column again, using the exact name displayed in the output above
# Sweden = Sweden.rename(columns={
#     'GM - What is your households total annual gross income before taxes?': 'Range_household_income'
# })

# Sweden.columns = Sweden.columns.str.strip() # Strip any extra whitespace from column names just in case
# print(Sweden.columns)

In [64]:
Sweden.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78236,25/11/2024 17:32:33,Complete,80.70.159.126,12.9076,56.438099,Sweden,Båstad,27.0,269 25,...,5,4,4,2,47,5,6,2,2,2
1,78238,25/11/2024 17:33:37,Complete,151.236.203.160,18.0653,59.327400,Sweden,Stockholm,26.0,163 94,...,5,6,4,1,27,3,6,4,1,1

In [65]:
# Convert the columns to string
Sweden['Gender'] = Sweden['Gender'].astype(str)
Sweden['highest level of education you have completed?'] = Sweden['highest level of education you have completed?'].astype(str)
Sweden['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Sweden['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Sweden['Region'] = Sweden['Region'].astype(str)
Sweden['Age Range'] = Sweden['Age Range'].astype(str)
Sweden['Range_household_income'] = Sweden['Range_household_income'].astype(str)
Sweden['best applies to the home you live in?'] = Sweden['best applies to the home you live in?'].astype(str)
Sweden['decision maker'] = Sweden['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Sweden['Gender'] = Sweden['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Sweden['highest level of education you have completed?'] = Sweden['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Sweden['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Sweden['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Sweden['best applies to the home you live in?'] = Sweden['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Sweden['Age Range'] = Sweden['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Sweden['decision maker'] = Sweden['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Sweden['Region'] = Sweden['Region'].replace({
    '1': 'North',
    '2': 'Middle',
    '3': 'West',
    '4': 'South',
    '5': 'Southeast',
    '6': 'East'
})

Sweden['Range_household_income'] = Sweden['Range_household_income'].replace({
    '1': 'Up to 99,999 kr',
    '2': '100,000 kr - 199,999 kr',
    '3': '200,000 kr - 299,999 kr',
    '4': '300,000 kr - 399,999 kr',
    '5': '400,000 kr - 499,999 kr',
    '6': '500,000 kr - 599,999 kr',
    '7': '600,000 kr - 699,999 kr',
    '8': '700,000 kr - 799,999 kr',
    '9': '800,000 kr or more ',
    '99': 'Dont know / Prefer not to answer'
})

print(Sweden.head())

   Response ID       Date Submitted    Status       IP Address  Longitude  \
0        78236  25/11/2024 17:32:33  Complete    80.70.159.126  12.907600
1        78238  25/11/2024 17:33:37  Complete  151.236.203.160  18.065300
2        78241  25/11/2024 17:34:49  Complete      78.70.93.61  17.979601
3        78246  25/11/2024 17:35:50  Complete     151.177.1.96  18.065300
4        78248  25/11/2024 17:34:18  Complete   213.89.157.239  17.916700

    Latitude Country       City  State/Region  Postal  ...  \
0  56.438099  Sweden     Båstad          27.0  269 25  ...
1  59.327400  Sweden  Stockholm          26.0  163 94  ...
2  59.309799  Sweden  Hägersten          26.0  129 40  ...
3  59.327400  Sweden  Stockholm          26.0  163 94  ...
4  59.349998  Sweden     Bromma          26.0  167 37  ...

   Which country are you currently residing in?  Region  \
0                                             5   South
1                                             5    East
2                                             5  Middle
3                                             5  Middle
4                                             5  Middle

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                             Urban city/ large town                 Female
1                             Urban city/ large town                   Male
2                             Urban city/ large town                 Female
3                             Urban city/ large town                 Female
4                             Urban city/ large town                 Female

  Age  Age Range   Range_household_income  \
0  47      45-60  500,000 kr - 599,999 kr
1  27      25-34  500,000 kr - 599,999 kr
2  28      25-34  400,000 kr - 499,999 kr
3  39      35-44  300,000 kr - 399,999 kr
4  33      25-34      800,000 kr or more

   highest level of education you have completed?  \
0                     Middle School / High School
1                                      University
2                     Middle School / High School
3                     Middle School / High School
4                                      University

   best applies to the home you live in?  \
0                              I rent it
1                               I own it
2                              I rent it
3                              I rent it
4                               I own it

                                      decision maker
0  I share responsibility with someone else in th...
1  I am solely responsible for choosing the domes...
2  I am solely responsible for choosing the domes...
3  I share responsibility with someone else in th...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [66]:
print(Sweden['Range_household_income'].value_counts(), "\n")
print(Sweden['Region'].value_counts())

Range_household_income
800,000 kr or more                  72
300,000 kr - 399,999 kr             59
400,000 kr - 499,999 kr             50
100,000 kr - 199,999 kr             41
700,000 kr - 799,999 kr             40
200,000 kr - 299,999 kr             40
600,000 kr - 699,999 kr             32
500,000 kr - 599,999 kr             29
Up to 99,999 kr                     25
Dont know / Prefer not to answer    12
Name: count, dtype: int64

Region
South        98
East         97
West         85
Middle       65
North        30
Southeast    25
Name: count, dtype: int64

In [67]:
Sweden.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78236,25/11/2024 17:32:33,Complete,80.70.159.126,12.9076,56.438099,Sweden,Båstad,27.0,269 25,...,5,South,Urban city/ large town,Female,47,45-60,"500,000 kr - 599,999 kr",Middle School / High School,I rent it,I share responsibility with someone else in th...
1,78238,25/11/2024 17:33:37,Complete,151.236.203.160,18.0653,59.327400,Sweden,Stockholm,26.0,163 94,...,5,East,Urban city/ large town,Male,27,25-34,"500,000 kr - 599,999 kr",University,I own it,I am solely responsible for choosing the domes...

### Italy

In [68]:
Italy.columns = Italy.columns.str.strip() # Clean up any extra whitespace in column names
print(Italy.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'IT - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [69]:
# Rename specific columns
Italy = Italy.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'IT - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Italy.columns = Italy.columns.str.strip() # Clean up any extra whitespace in column names
print(Italy.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [70]:
Italy.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78233,25/11/2024 17:36:42,Complete,151.90.192.193,12.5126,41.8904,Italy,Rome,07,00143,...,3,1,2,1,47,5,3,4,1,1
1,78237,25/11/2024 17:34:05,Complete,151.47.63.30,12.1097,43.1479,Italy,NaN,NaN,NaN,...,3,7,2,1,54,5,2,5,1,2

In [71]:
# Convert the columns to string
Italy['Gender'] = Italy['Gender'].astype(str)
Italy['highest level of education you have completed?'] = Italy['highest level of education you have completed?'].astype(str)
Italy['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Italy['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Italy['Region'] = Italy['Region'].astype(str)
Italy['Age Range'] = Italy['Age Range'].astype(str)
Italy['Range_household_income'] = Italy['Range_household_income'].astype(str)
Italy['best applies to the home you live in?'] = Italy['best applies to the home you live in?'].astype(str)
Italy['decision maker'] = Italy['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Italy['Gender'] = Italy['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Italy['highest level of education you have completed?'] = Italy['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Italy['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Italy['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Italy['best applies to the home you live in?'] = Italy['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Italy['Age Range'] = Italy['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Italy['decision maker'] = Italy['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Italy['Region'] = Italy['Region'].replace({
    '1': 'Abruzzo/Basilacata/Calabria/Friuli-Venezia Giulia/Liguria/Marche/Molise/Sardegna/Trentino-Alto Adige/Umbria/Veneto',
    '2': 'Campania',
    '3': 'Emilia-Romagna  ',
    '4': 'Lazio',
    '5': 'Lombardia',
    '6': 'Piemonte',
    '7': 'Puglia',
    '8': 'Sicilia',
    '9': 'Toscana'
})

Italy['Range_household_income'] = Italy['Range_household_income'].replace({
    '1': 'Up to € 20,000',
    '2': '€ 20,000 - € 29,999',
    '3': '€ 30,000 - € 44,999',
    '4': '€ 45,000 - € 74,999',
    '5': '€ 75,000 - € 120,000 or more',
    '99': 'Don’t know / prefer not to answer'
})

print(Italy.head())

   Response ID       Date Submitted    Status      IP Address  Longitude  \
0        78233  25/11/2024 17:36:42  Complete  151.90.192.193    12.5126
1        78237  25/11/2024 17:34:05  Complete    151.47.63.30    12.1097
2        78242  25/11/2024 17:34:12  Complete    62.98.62.160    14.2385
3        78300  25/11/2024 17:35:34  Complete  185.11.192.205     9.1922
4        78315  25/11/2024 17:33:55  Complete   95.250.109.50    14.9956

    Latitude Country     City State/Region Postal  ...  \
0  41.890400   Italy     Rome           07  00143  ...
1  43.147900   Italy      NaN          NaN    NaN  ...
2  40.867001   Italy   Naples           04  80147  ...
3  45.472198   Italy    Milan           09  20153  ...
4  37.289398   Italy  Lentini           15  96016  ...

   Which country are you currently residing in?  \
0                                             3
1                                             3
2                                             3
3                                             3
4                                             3

                                              Region  \
0  Abruzzo/Basilacata/Calabria/Friuli-Venezia Giu...
1                                             Puglia
2                                          Lombardia
3                                          Lombardia
4                                            Sicilia

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                                         Small Town                   Male
1                                         Small Town                   Male
2                             Urban city/ large town                 Female
3                             Urban city/ large town                   Male
4                                     Rural/ village                   Male

  Age  Age Range  Range_household_income  \
0  47      45-60     € 30,000 - € 44,999
1  54      45-60     € 20,000 - € 29,999
2  28      25-34     € 45,000 - € 74,999
3  57      45-60     € 30,000 - € 44,999
4  59      45-60          Up to € 20,000

   highest level of education you have completed?  \
0                                      University
1                           Post graduate studies
2                                      University
3                    Primary and Secondary school
4    Diploma / Technical College / Junior College

   best applies to the home you live in?  \
0                               I own it
1                               I own it
2                               I own it
3                               I own it
4                               I own it

                                      decision maker
0  I am solely responsible for choosing the domes...
1  I share responsibility with someone else in th...
2  I am solely responsible for choosing the domes...
3  I share responsibility with someone else in th...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [72]:
print(Italy['Range_household_income'].value_counts(), "\n")
print(Italy['Region'].value_counts())

Range_household_income
€ 30,000 - € 44,999                  127
€ 45,000 - € 74,999                   84
€ 20,000 - € 29,999                   82
Up to € 20,000                        58
€ 75,000 - € 120,000 or more          36
Don’t know / prefer not to answer     11
Name: count, dtype: int64

Region
Abruzzo/Basilacata/Calabria/Friuli-Venezia Giulia/Liguria/Marche/Molise/Sardegna/Trentino-Alto Adige/Umbria/Veneto    92
Lombardia                                                                                                             82
Lazio                                                                                                                 48
Piemonte                                                                                                              38
Campania                                                                                                              36
Emilia-Romagna                                                                                                        32
Sicilia                                                                                                               30
Puglia                                                                                                                20
Toscana                                                                                                               20
Name: count, dtype: int64

In [73]:
Italy.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78233,25/11/2024 17:36:42,Complete,151.90.192.193,12.5126,41.8904,Italy,Rome,07,00143,...,3,Abruzzo/Basilacata/Calabria/Friuli-Venezia Giu...,Small Town,Male,47,45-60,"€ 30,000 - € 44,999",University,I own it,I am solely responsible for choosing the domes...
1,78237,25/11/2024 17:34:05,Complete,151.47.63.30,12.1097,43.1479,Italy,NaN,NaN,NaN,...,3,Puglia,Small Town,Male,54,45-60,"€ 20,000 - € 29,999",Post graduate studies,I own it,I share responsibility with someone else in th...

### Poland

In [74]:
Poland.columns = Poland.columns.str.strip() # Clean up any extra whitespace in column names
print(Poland.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'PO - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [75]:
# Rename specific columns
Poland = Poland.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'PO - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Poland.columns = Poland.columns.str.strip() # Clean up any extra whitespace in column names
print(Poland.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [76]:
Poland.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78295,25/11/2024 17:34:36,Complete,46.148.154.65,22.200199,49.561901,Poland,Sanok,80.0,38-500,...,4,9,3,2,52,5,11,5,1,2
1,78297,25/11/2024 17:42:57,Complete,213.134.171.239,21.036200,52.239399,Poland,NaN,NaN,NaN,...,4,7,4,2,65,6,5,3,1,1

In [77]:
# Convert the columns to string
Poland['Gender'] = Poland['Gender'].astype(str)
Poland['highest level of education you have completed?'] = Poland['highest level of education you have completed?'].astype(str)
Poland['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Poland['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Poland['Region'] = Poland['Region'].astype(str)
Poland['Age Range'] = Poland['Age Range'].astype(str)
Poland['Range_household_income'] = Poland['Range_household_income'].astype(str)
Poland['best applies to the home you live in?'] = Poland['best applies to the home you live in?'].astype(str)
Poland['decision maker'] = Poland['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Poland['Gender'] = Poland['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Poland['highest level of education you have completed?'] = Poland['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Poland['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Poland['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Poland['best applies to the home you live in?'] = Poland['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Poland['Age Range'] = Poland['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Poland['decision maker'] = Poland['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Poland['Region'] = Poland['Region'].replace({
    '1': 'Dolnoslaskie',
    '2': 'Kujawsko-Pomorskie',
    '3': 'Lubelskie',
    '4': 'Lubuskie',
    '5': 'Lódzkie',
    '6': 'Malopolskie',
    '7': 'Mazowieckie',
    '8': 'Opolskie',
    '9': 'Podkarpackie',
    '10': 'Podlaskie',
    '11': 'Pomorskie',
    '12': 'Slaskie',
    '13': 'Swietokrzyskie',
    '14': 'Warminsko-Mazurskie',
    '15': 'Wielkopolskie',
    '16': 'Zachodniopomorskie'
})

Poland['Range_household_income'] = Poland['Range_household_income'].replace({
    '1': 'up to 999 zł',
    '2': '1000-1999 zł',
    '3': '2000-2999 zł',
    '4': '3000-3999 zł',
    '5': '4000- 4999 zł',
    '6': '5000-5999 zł',
    '7': '6000-6999 zł',
    '8': '7000-7999 zł',
    '9': '8000-8999 zł',
    '10': '9000-9999 zł',
    '11': '10000-10999 zł',
    '12': '11000-11999 zł',
    '13': '12000-12999 zł',
    '14': '13000-13999 zł',
    '15': '14000 or more',
    '99': 'Do not wish to answer/Don’t know'
})

print(Poland.head())

   Response ID       Date Submitted    Status       IP Address  Longitude  \
0        78295  25/11/2024 17:34:36  Complete    46.148.154.65  22.200199
1        78297  25/11/2024 17:42:57  Complete  213.134.171.239  21.036200
2        78309  25/11/2024 17:33:43  Complete     81.95.194.42  18.404100
3        78317  25/11/2024 17:38:53  Complete    188.146.36.99  21.002600
4        78344  25/11/2024 17:37:44  Complete    194.152.51.90  15.720500

    Latitude Country      City  State/Region  Postal  ...  \
0  49.561901  Poland     Sanok          80.0  38-500  ...
1  52.239399  Poland       NaN           NaN     NaN  ...
2  54.390598  Poland    Banino          82.0  80-297  ...
3  52.248402  Poland    Warsaw          78.0  00-202  ...
4  51.800499  Poland  Nowa Sol          76.0  67-100  ...

   Which country are you currently residing in?              Region  \
0                                             4        Podkarpackie
1                                             4         Mazowieckie
2                                             4       Wielkopolskie
3                                             4  Zachodniopomorskie
4                                             4            Lubuskie

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                           Suburban/ city outskirts                 Female
1                             Urban city/ large town                 Female
2                                     Rural/ village                 Female
3                             Urban city/ large town                 Female
4                                         Small Town                 Female

  Age  Age Range  Range_household_income  \
0  52      45-60          10000-10999 zł
1  65      61-70           4000- 4999 zł
2  38      35-44            9000-9999 zł
3  37      35-44            8000-8999 zł
4  31      25-34            9000-9999 zł

   highest level of education you have completed?  \
0                           Post graduate studies
1    Diploma / Technical College / Junior College
2    Diploma / Technical College / Junior College
3                                      University
4                                      University

   best applies to the home you live in?  \
0                               I own it
1                               I own it
2                               I own it
3                               I own it
4                              I rent it

                                      decision maker
0  I share responsibility with someone else in th...
1  I am solely responsible for choosing the domes...
2  I am solely responsible for choosing the domes...
3  I share responsibility with someone else in th...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [78]:
print(Poland['Range_household_income'].value_counts(), "\n")
print(Poland['Region'].value_counts())

Range_household_income
4000- 4999 zł                       53
7000-7999 zł                        50
5000-5999 zł                        47
3000-3999 zł                        44
6000-6999 zł                        44
9000-9999 zł                        29
14000 or more                       27
8000-8999 zł                        23
10000-10999 zł                      16
1000-1999 zł                        15
2000-2999 zł                        12
12000-12999 zł                       9
Do not wish to answer/Don’t know     9
13000-13999 zł                       8
11000-11999 zł                       8
up to 999 zł                         6
Name: count, dtype: int64

Region
Mazowieckie            55
Slaskie                53
Dolnoslaskie           34
Malopolskie            32
Wielkopolskie          26
Podkarpackie           26
Pomorskie              26
Kujawsko-Pomorskie     24
Lódzkie                22
Lubelskie              22
Zachodniopomorskie     20
Swietokrzyskie         16
Warminsko-Mazurskie    15
Opolskie               10
Podlaskie              10
Lubuskie                9
Name: count, dtype: int64

In [79]:
Poland.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78295,25/11/2024 17:34:36,Complete,46.148.154.65,22.200199,49.561901,Poland,Sanok,80.0,38-500,...,4,Podkarpackie,Suburban/ city outskirts,Female,52,45-60,10000-10999 zł,Post graduate studies,I own it,I share responsibility with someone else in th...
1,78297,25/11/2024 17:42:57,Complete,213.134.171.239,21.036200,52.239399,Poland,NaN,NaN,NaN,...,4,Mazowieckie,Urban city/ large town,Female,65,61-70,4000- 4999 zł,Diploma / Technical College / Junior College,I own it,I am solely responsible for choosing the domes...

### Vietnam

In [80]:
Vietnam.columns = Vietnam.columns.str.strip() # Clean up any extra whitespace in column names
print(Vietnam.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'language', 'BRID',
       'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month', 'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'VN - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [81]:
# Rename specific columns
Vietnam = Vietnam.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'VN - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Vietnam.columns = Vietnam.columns.str.strip() # Clean up any extra whitespace in column names
print(Vietnam.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'language', 'BRID',
       'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month', 'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [82]:
# Convert the columns to string
Vietnam['Gender'] = Vietnam['Gender'].astype(str)
Vietnam['highest level of education you have completed?'] = Vietnam['highest level of education you have completed?'].astype(str)
Vietnam['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Vietnam['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Vietnam['Region'] = Vietnam['Region'].astype(str)
Vietnam['Age Range'] = Vietnam['Age Range'].astype(str)
Vietnam['Range_household_income'] = Vietnam['Range_household_income'].astype(str)
Vietnam['best applies to the home you live in?'] = Vietnam['best applies to the home you live in?'].astype(str)
Vietnam['decision maker'] = Vietnam['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Vietnam['Gender'] = Vietnam['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Vietnam['highest level of education you have completed?'] = Vietnam['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Vietnam['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Vietnam['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Vietnam['best applies to the home you live in?'] = Vietnam['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Vietnam['Age Range'] = Vietnam['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Vietnam['decision maker'] = Vietnam['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Vietnam['Region'] = Vietnam['Region'].replace({
    '1': 'Ho Chi Minh',
    '2': 'Hanoi',
    '97': 'Others'
})

Vietnam['Range_household_income'] = Vietnam['Range_household_income'].replace({
    '1': 'Less than VND 10,500,001',
    '2': 'VND 10,500,001-15,000,000',
    '3': 'VND 15,000,001-20,000,000',
    '4': 'VND 20,000,001-30,000,000',
    '5': 'Above VND 30,000,000',
    '99': 'Do not wish to answer/Don’t know'
})

print(Vietnam.head())

   Response ID       Date Submitted    Status       IP Address   Longitude  \
0        78271  25/11/2024 17:34:50  Complete  171.250.166.107  106.535500
1        78275  25/11/2024 17:39:12  Complete   113.185.77.116  106.658096
2        78287  25/11/2024 17:41:00  Complete    42.115.165.86  105.843201
3        78291  25/11/2024 17:35:24  Complete   59.153.254.217  105.851601
4        78358  25/11/2024 17:39:28  Complete   113.185.74.220  106.658096

    Latitude  Country              City  State/Region  language  ...  \
0  10.630600  Vietnam            My Yen          24.0        10  ...
1  10.832600  Vietnam  Ho Chi Minh City          20.0        10  ...
2  21.594101  Vietnam       Thái Nguyên          85.0        10  ...
3  21.031300  Vietnam             Hanoi          44.0        10  ...
4  10.832600  Vietnam  Ho Chi Minh City          20.0        10  ...

  Which country are you currently residing in?       Region  \
0                                            9  Ho Chi Minh
1                                            9        Hanoi
2                                            9  Ho Chi Minh
3                                            9        Hanoi
4                                            9  Ho Chi Minh

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                             Urban city/ large town                 Female
1                             Urban city/ large town                 Female
2                             Urban city/ large town                   Male
3                             Urban city/ large town                 Female
4                             Urban city/ large town                 Female

   Age  Age Range     Range_household_income  \
0   31      25-34  VND 20,000,001-30,000,000
1   34      25-34  VND 20,000,001-30,000,000
2   32      25-34       Above VND 30,000,000
3   34      25-34  VND 20,000,001-30,000,000
4   28      25-34  VND 15,000,001-20,000,000

   highest level of education you have completed?  \
0                                      University
1                                      University
2                                      University
3                                      University
4    Diploma / Technical College / Junior College

   best applies to the home you live in?  \
0                               I own it
1                               I own it
2                              I rent it
3                               I own it
4                              I rent it

                                      decision maker
0  I am solely responsible for choosing the domes...
1  I am solely responsible for choosing the domes...
2  I am solely responsible for choosing the domes...
3  I am solely responsible for choosing the domes...
4  I am solely responsible for choosing the domes...

[5 rows x 31 columns]

In [83]:
Vietnam.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,language,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78271,25/11/2024 17:34:50,Complete,171.250.166.107,106.535500,10.6306,Vietnam,My Yen,24.0,10,...,9,Ho Chi Minh,Urban city/ large town,Female,31,25-34,"VND 20,000,001-30,000,000",University,I own it,I am solely responsible for choosing the domes...
1,78275,25/11/2024 17:39:12,Complete,113.185.77.116,106.658096,10.8326,Vietnam,Ho Chi Minh City,20.0,10,...,9,Hanoi,Urban city/ large town,Female,34,25-34,"VND 20,000,001-30,000,000",University,I own it,I am solely responsible for choosing the domes...

In [84]:
print(Vietnam['Range_household_income'].value_counts(), "\n")
print(Vietnam['Region'].value_counts())

Range_household_income
VND 10,500,001-15,000,000    115
VND 15,000,001-20,000,000    102
VND 20,000,001-30,000,000     76
Above VND 30,000,000          73
Less than VND 10,500,001      34
Name: count, dtype: int64

Region
Ho Chi Minh    201
Hanoi          142
Others          57
Name: count, dtype: int64

In [85]:
Vietnam.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,language,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78271,25/11/2024 17:34:50,Complete,171.250.166.107,106.535500,10.6306,Vietnam,My Yen,24.0,10,...,9,Ho Chi Minh,Urban city/ large town,Female,31,25-34,"VND 20,000,001-30,000,000",University,I own it,I am solely responsible for choosing the domes...
1,78275,25/11/2024 17:39:12,Complete,113.185.77.116,106.658096,10.8326,Vietnam,Ho Chi Minh City,20.0,10,...,9,Hanoi,Urban city/ large town,Female,34,25-34,"VND 20,000,001-30,000,000",University,I own it,I am solely responsible for choosing the domes...

### Switzerland

In [86]:
Switzerland.columns = Switzerland.columns.str.strip() # Clean up any extra whitespace in column names
print(Switzerland.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'SZ - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [87]:
# Rename specific columns
Switzerland = Switzerland.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'SZ - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Switzerland.columns = Switzerland.columns.str.strip() # Clean up any extra whitespace in column names
print(Switzerland.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [88]:
# Convert the columns to string
Switzerland['Gender'] = Switzerland['Gender'].astype(str)
Switzerland['highest level of education you have completed?'] = Switzerland['highest level of education you have completed?'].astype(str)
Switzerland['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Switzerland['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Switzerland['Region'] = Switzerland['Region'].astype(str)
Switzerland['Age Range'] = Switzerland['Age Range'].astype(str)
Switzerland['Range_household_income'] = Switzerland['Range_household_income'].astype(str)
Switzerland['best applies to the home you live in?'] = Switzerland['best applies to the home you live in?'].astype(str)
Switzerland['decision maker'] = Switzerland['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Switzerland['Gender'] = Switzerland['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Switzerland['highest level of education you have completed?'] = Switzerland['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Switzerland['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Switzerland['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Switzerland['best applies to the home you live in?'] = Switzerland['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Switzerland['Age Range'] = Switzerland['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Switzerland['decision maker'] = Switzerland['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Switzerland['Region'] = Switzerland['Region'].replace({
    '1': 'Geneva',
    '2': 'Valais',
    '3': 'Vaud',
    '4': 'Bern',
    '5': 'Fribourg',
    '6': 'Jura',
    '7': 'Neuchatel',
    '8': 'Solothurn',
    '9': 'Aargau',
    '10': 'Basel-Landschaft',
    '11': 'Basel-Stadt',
    '12': 'Zurich',
    '13': 'Appenzell A. Rh',
    '14': 'Appenzell I. Rh',
    '15': 'Glarus',
    '16': 'Graubunden',
    '17': 'Schaffhausen',
    '18': 'St.Gallen',
    '19': 'Thurgau',
    '20': 'Lucerne',
    '21': 'Nidwald',
    '22': 'Obwald',
    '23': 'Schwyz',
    '24': 'Uri',
    '25': 'Zug',
    '26': 'Ticino'
})

Switzerland['Range_household_income'] = Switzerland['Range_household_income'].replace({
    '1': 'Upto 40 000 CHF',
    '2': '40 000 CHF - 59 999 CHF',
    '3': '60 000 CHF - 79 999 CHF',
    '4': '80 000 CHF - 99 999 CHF',
    '5': '100 000 CHF - 119 999 CHF',
    '6': '120 000 CHF - 139 999 CHF',
    '7': '140 000 CHF - 159 999 CHF',
    '8': '160 000 CHF - 179 999 CHF',
    '9': '180 000 CHF - 199 999 CHF',
    '10': '200 000 CHF - 219 999 CHF',
    '11': '220 000 CHF - 239 999 CHF',
    '12': '240 000 CHF - 259 999 CHF',
    '13': '260 000 CHF - 279 999 CHF',
    '14': '280 000 CHF - 299 999 CHF',
    '15': '300 000 CHF or more',
    '99': 'Don’t know / prefer not to answer'
})

print(Switzerland.head())

   Response ID       Date Submitted    Status       IP Address  Longitude  \
0        78375  25/11/2024 17:38:34  Complete   80.218.178.224     8.4623
1        78387  25/11/2024 17:34:18  Complete  194.230.146.147     6.1385
2        78581  25/11/2024 17:38:31  Complete     178.38.6.170     9.3696
3        78735  25/11/2024 17:38:49  Complete  194.230.161.138     8.9790
4        78849  25/11/2024 17:42:40  Complete     93.38.156.29    12.1097

    Latitude      Country          City  State/Region Postal  ...  \
0  47.438400  Switzerland    Regensdorf          25.0   8105  ...
1  46.195301  Switzerland        Geneve           7.0   1201  ...
2  47.423401  Switzerland  Saint Gallen          15.0   9000  ...
3  46.018002  Switzerland    Pregassona          20.0   6963  ...
4  43.147900        Italy           NaN           NaN    NaN  ...

   Which country are you currently residing in?        Region  \
0                                             6     Neuchatel
1                                             6        Geneva
2                                             6        Zurich
3                                             6  Schaffhausen
4                                             6        Zurich

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                                         Small Town                   Male
1                             Urban city/ large town                   Male
2                             Urban city/ large town                   Male
3                                         Small Town                   Male
4                             Urban city/ large town                 Female

  Age  Age Range     Range_household_income  \
0  27      25-34    80 000 CHF - 99 999 CHF
1  45      45-60            Upto 40 000 CHF
2  41      35-44  240 000 CHF - 259 999 CHF
3  33      25-34    60 000 CHF - 79 999 CHF
4  62      61-70    40 000 CHF - 59 999 CHF

   highest level of education you have completed?  \
0    Diploma / Technical College / Junior College
1    Diploma / Technical College / Junior College
2                           Post graduate studies
3                     Middle School / High School
4                     Middle School / High School

   best applies to the home you live in?  \
0                              I rent it
1                              I rent it
2                              I rent it
3                              I rent it
4                               I own it

                                      decision maker
0  I share responsibility with someone else in th...
1  I am solely responsible for choosing the domes...
2  I share responsibility with someone else in th...
3  I share responsibility with someone else in th...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [89]:
Switzerland.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78375,25/11/2024 17:38:34,Complete,80.218.178.224,8.4623,47.438400,Switzerland,Regensdorf,25.0,8105,...,6,Neuchatel,Small Town,Male,27,25-34,80 000 CHF - 99 999 CHF,Diploma / Technical College / Junior College,I rent it,I share responsibility with someone else in th...
1,78387,25/11/2024 17:34:18,Complete,194.230.146.147,6.1385,46.195301,Switzerland,Geneve,7.0,1201,...,6,Geneva,Urban city/ large town,Male,45,45-60,Upto 40 000 CHF,Diploma / Technical College / Junior College,I rent it,I am solely responsible for choosing the domes...

In [90]:
print(Switzerland['Range_household_income'].value_counts(), "\n")
print(Switzerland['Region'].value_counts())

Range_household_income
80 000 CHF - 99 999 CHF              76
60 000 CHF - 79 999 CHF              75
40 000 CHF - 59 999 CHF              60
Upto 40 000 CHF                      55
100 000 CHF - 119 999 CHF            26
280 000 CHF - 299 999 CHF            24
260 000 CHF - 279 999 CHF            22
240 000 CHF - 259 999 CHF            10
Don’t know / prefer not to answer     9
180 000 CHF - 199 999 CHF             8
220 000 CHF - 239 999 CHF             8
160 000 CHF - 179 999 CHF             8
200 000 CHF - 219 999 CHF             6
120 000 CHF - 139 999 CHF             6
140 000 CHF - 159 999 CHF             5
Name: count, dtype: int64

Region
Zurich              73
Bern                57
Vaud                50
Lucerne             37
Aargau              25
Geneva              25
St.Gallen           19
Basel-Landschaft    13
Solothurn           12
Valais              12
Ticino              12
Neuchatel           11
Thurgau              9
Basel-Stadt          8
Fribourg             8
Graubunden           7
Nidwald              4
Schaffhausen         4
Schwyz               3
Appenzell A. Rh      2
Zug                  2
Obwald               2
Jura                 2
Appenzell I. Rh      1
Name: count, dtype: int64

In [91]:
Switzerland.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78375,25/11/2024 17:38:34,Complete,80.218.178.224,8.4623,47.438400,Switzerland,Regensdorf,25.0,8105,...,6,Neuchatel,Small Town,Male,27,25-34,80 000 CHF - 99 999 CHF,Diploma / Technical College / Junior College,I rent it,I share responsibility with someone else in th...
1,78387,25/11/2024 17:34:18,Complete,194.230.146.147,6.1385,46.195301,Switzerland,Geneve,7.0,1201,...,6,Geneva,Urban city/ large town,Male,45,45-60,Upto 40 000 CHF,Diploma / Technical College / Junior College,I rent it,I am solely responsible for choosing the domes...

### UK

In [92]:
UK.columns = UK.columns.str.strip() # Clean up any extra whitespace in column names
print(UK.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'UK - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [93]:
# Rename specific columns
UK = UK.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'UK - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

UK.columns = UK.columns.str.strip() # Clean up any extra whitespace in column names
print(UK.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [94]:
# Convert the columns to string
UK['Gender'] = UK['Gender'].astype(str)
UK['highest level of education you have completed?'] = UK['highest level of education you have completed?'].astype(str)
UK['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = UK['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
UK['Region'] = UK['Region'].astype(str)
UK['Age Range'] = UK['Age Range'].astype(str)
UK['Range_household_income'] = UK['Range_household_income'].astype(str)
UK['best applies to the home you live in?'] = UK['best applies to the home you live in?'].astype(str)
UK['decision maker'] = UK['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
UK['Gender'] = UK['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

UK['highest level of education you have completed?'] = UK['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

UK['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = UK['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

UK['best applies to the home you live in?'] = UK['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

UK['Age Range'] = UK['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

UK['decision maker'] = UK['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
UK['Region'] = UK['Region'].replace({
    '1': 'East Anglia',
    '2': 'Greater London',
    '3': 'South East',
    '4': 'Midlands',
    '5': 'South Wes',
    '6': 'Wales',
    '7': 'North East',
    '8': 'North West',
    '9': 'Scotland',
    '10': 'Yorkshire'
})

UK['Range_household_income'] = UK['Range_household_income'].replace({
    '1': 'Up to £10,000',
    '2': '£10,000 - £16,999 ',
    '3': '£17,000 - £22,999',
    '4': '£23,000 - £29,999',
    '5': '£30,000 - £39,999',
    '6': '£40,000 - £49,999',
    '7': '£50,000 - £59,999',
    '8': '£60,000 or above',
    '99': 'Do not wish to answer/Don’t know'
})

print(UK.head())

   Response ID       Date Submitted    Status       IP Address  Longitude  \
0        78251  25/11/2024 17:33:39  Complete   188.241.40.227    -0.8951
1        78258  25/11/2024 17:48:05  Complete     92.40.171.86    -0.1224
2        78259  25/11/2024 17:38:10  Complete    90.207.215.19    -1.0664
3        78261  25/11/2024 17:31:33  Complete  157.125.184.202    -0.1224
4        78262  25/11/2024 17:32:43  Complete  109.147.249.173    -2.9759

    Latitude         Country         City State/Region Postal  ...  \
0  52.283501  United Kingdom  Northampton           J1    NN2  ...
1  51.496399  United Kingdom          NaN          NaN    NaN  ...
2  50.820000  United Kingdom   Portsmouth           K6    PO2  ...
3  51.496399  United Kingdom          NaN          NaN    NaN  ...
4  53.411301  United Kingdom    Liverpool           H8     L8  ...

   Which country are you currently residing in?          Region  \
0                                             8      North West
1                                             8  Greater London
2                                             8        Midlands
3                                             8      North West
4                                             8      North West

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                             Urban city/ large town                 Female
1                                         Small Town                   Male
2                             Urban city/ large town                   Male
3                                         Small Town                   Male
4                             Urban city/ large town                 Female

  Age  Age Range  Range_household_income  \
0  36      35-44       £50,000 - £59,999
1  45      45-60       £23,000 - £29,999
2  38      35-44        £60,000 or above
3  31      25-34       £50,000 - £59,999
4  32      25-34        £60,000 or above

   highest level of education you have completed?  \
0                                      University
1                     Middle School / High School
2    Diploma / Technical College / Junior College
3    Diploma / Technical College / Junior College
4                                      University

   best applies to the home you live in?  \
0                              I rent it
1                               I own it
2                               I own it
3                               I own it
4                              I rent it

                                      decision maker
0  I am solely responsible for choosing the domes...
1  I share responsibility with someone else in th...
2  I am solely responsible for choosing the domes...
3  I am solely responsible for choosing the domes...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [95]:
UK.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78251,25/11/2024 17:33:39,Complete,188.241.40.227,-0.8951,52.283501,United Kingdom,Northampton,J1,NN2,...,8,North West,Urban city/ large town,Female,36,35-44,"£50,000 - £59,999",University,I rent it,I am solely responsible for choosing the domes...
1,78258,25/11/2024 17:48:05,Complete,92.40.171.86,-0.1224,51.496399,United Kingdom,NaN,NaN,NaN,...,8,Greater London,Small Town,Male,45,45-60,"£23,000 - £29,999",Middle School / High School,I own it,I share responsibility with someone else in th...

In [96]:
print(UK['Range_household_income'].value_counts(), "\n")
print(UK['Region'].value_counts())

Range_household_income
£60,000 or above                    86
£23,000 - £29,999                   63
£30,000 - £39,999                   60
£10,000 - £16,999                   44
£50,000 - £59,999                   42
£40,000 - £49,999                   32
Up to £10,000                       30
£17,000 - £22,999                   28
Do not wish to answer/Don’t know    11
Name: count, dtype: int64

Region
Midlands          74
Greater London    58
North West        57
South East        52
East Anglia       33
Scotland          27
North East        26
South Wes         26
Yorkshire         25
Wales             18
Name: count, dtype: int64

In [97]:
UK.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78251,25/11/2024 17:33:39,Complete,188.241.40.227,-0.8951,52.283501,United Kingdom,Northampton,J1,NN2,...,8,North West,Urban city/ large town,Female,36,35-44,"£50,000 - £59,999",University,I rent it,I am solely responsible for choosing the domes...
1,78258,25/11/2024 17:48:05,Complete,92.40.171.86,-0.1224,51.496399,United Kingdom,NaN,NaN,NaN,...,8,Greater London,Small Town,Male,45,45-60,"£23,000 - £29,999",Middle School / High School,I own it,I share responsibility with someone else in th...

### Australia

In [98]:
Australia.columns = Australia.columns.str.strip() # Clean up any extra whitespace in column names
print(Australia.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'AU - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [99]:
# Rename specific columns
Australia = Australia.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'AU - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Australia.columns = Australia.columns.str.strip() # Clean up any extra whitespace in column names
print(Australia.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [100]:
# Convert the columns to string
Australia['Gender'] = Australia['Gender'].astype(str)
Australia['highest level of education you have completed?'] = Australia['highest level of education you have completed?'].astype(str)
Australia['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Australia['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Australia['Region'] = Australia['Region'].astype(str)
Australia['Age Range'] = Australia['Age Range'].astype(str)
Australia['Range_household_income'] = Australia['Range_household_income'].astype(str)
Australia['best applies to the home you live in?'] = Australia['best applies to the home you live in?'].astype(str)
Australia['decision maker'] = Australia['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Australia['Gender'] = Australia['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Australia['highest level of education you have completed?'] = Australia['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Australia['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Australia['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Australia['best applies to the home you live in?'] = Australia['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Australia['Age Range'] = Australia['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Australia['decision maker'] = Australia['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Australia['Region'] = Australia['Region'].replace({
    '1': 'New South Wales',
    '2': 'Victoria',
    '3': 'Queensland',
    '4': 'Western/South Australia',
    '97': 'Others',
})

Australia['Range_household_income'] = Australia['Range_household_income'].replace({
    '1': 'Less than AUD 2,000',
    '2': 'AUD 2,000 - 4,000',
    '3': 'AUD 4,001 - 6,000',
    '4': 'AUD 6,001 - 8,000',
    '5': 'Above AUD 8,000',
    '99': 'Do not wish to answer/Don’t know'
})

print(Australia.head())

   Response ID       Date Submitted    Status       IP Address   Longitude  \
0        78293  25/11/2024 17:38:30  Complete     144.6.116.89  143.210403
1        78361  25/11/2024 17:33:51  Complete  149.167.183.242  145.006393
2        78394  25/11/2024 17:34:00  Complete   220.253.18.226  144.954407
3        78406  25/11/2024 17:38:52  Complete   101.183.16.139  143.210403
4        78429  25/11/2024 17:35:17  Complete   110.141.140.20  149.128296

    Latitude    Country       City State/Region  Postal  ...  \
0 -33.493999  Australia        NaN          NaN     NaN  ...
1 -37.785999  Australia  Northcote           07  3070.0  ...
2 -37.810902  Australia  Melbourne           07  3000.0  ...
3 -33.493999  Australia        NaN          NaN     NaN  ...
4 -35.282799  Australia   Canberra           01  2601.0  ...

   Which country are you currently residing in?           Region  \
0                                             1  New South Wales
1                                             1           Others
2                                             1         Victoria
3                                             1  New South Wales
4                                             1           Others

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                             Urban city/ large town                 Female
1                           Suburban/ city outskirts                 Female
2                           Suburban/ city outskirts                   Male
3                             Urban city/ large town                   Male
4                               Prefer not to answer                   Male

  Age  Age Range  Range_household_income  \
0  35      35-44       AUD 6,001 - 8,000
1  25      25-34       AUD 6,001 - 8,000
2  42      35-44       AUD 4,001 - 6,000
3  36      35-44       AUD 4,001 - 6,000
4  36      35-44     Less than AUD 2,000

   highest level of education you have completed?  \
0                           Post graduate studies
1                                      University
2                                      University
3                                      University
4                    Primary and Secondary school

   best applies to the home you live in?  \
0                               I own it
1                              I rent it
2                              I rent it
3                              I rent it
4                              I rent it

                                      decision maker
0  I share responsibility with someone else in th...
1  I am solely responsible for choosing the domes...
2  I am solely responsible for choosing the domes...
3  I share responsibility with someone else in th...
4  I am solely responsible for choosing the domes...

[5 rows x 32 columns]

In [101]:
Australia.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78293,25/11/2024 17:38:30,Complete,144.6.116.89,143.210403,-33.493999,Australia,NaN,NaN,NaN,...,1,New South Wales,Urban city/ large town,Female,35,35-44,"AUD 6,001 - 8,000",Post graduate studies,I own it,I share responsibility with someone else in th...
1,78361,25/11/2024 17:33:51,Complete,149.167.183.242,145.006393,-37.785999,Australia,Northcote,07,3070.0,...,1,Others,Suburban/ city outskirts,Female,25,25-34,"AUD 6,001 - 8,000",University,I rent it,I am solely responsible for choosing the domes...

In [102]:
print(Australia['Range_household_income'].value_counts(), "\n")
print(Australia['Region'].value_counts())

Range_household_income
AUD 2,000 - 4,000                   108
Above AUD 8,000                      94
AUD 4,001 - 6,000                    76
AUD 6,001 - 8,000                    72
Less than AUD 2,000                  36
Do not wish to answer/Don’t know     11
Name: count, dtype: int64

Region
New South Wales            125
Victoria                   107
Queensland                  82
Western/South Australia     63
Others                      20
Name: count, dtype: int64

In [103]:
Australia.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78293,25/11/2024 17:38:30,Complete,144.6.116.89,143.210403,-33.493999,Australia,NaN,NaN,NaN,...,1,New South Wales,Urban city/ large town,Female,35,35-44,"AUD 6,001 - 8,000",Post graduate studies,I own it,I share responsibility with someone else in th...
1,78361,25/11/2024 17:33:51,Complete,149.167.183.242,145.006393,-37.785999,Australia,Northcote,07,3070.0,...,1,Others,Suburban/ city outskirts,Female,25,25-34,"AUD 6,001 - 8,000",University,I rent it,I am solely responsible for choosing the domes...

### Thailand

In [104]:
Thailand.columns = Thailand.columns.str.strip() # Clean up any extra whitespace in column names
print(Thailand.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?',
       'TH - Which region/city do you live in?',
       'Which of the following best describes the area in which you live?',
       'Are you?', 'Please type in your age...',
       'Please select your age range', 'Range_household_income',
       'What is the highest level of education you have completed?',
       'Which best applies to the home you live in?',
       'Which one of these applies to you?'],
      dtype='object')

In [105]:
# Rename specific columns
Thailand = Thailand.rename(columns={
    'Are you?': 'Gender',
    'Please type in your age...': 'Age',
    'Please select your age range': 'Age Range',
    # "SW - What is your household's total annual gross income before taxes?": 'Range_household_income',
    'What is the highest level of education you have completed?': 'highest level of education you have completed?',
    'Which of the following best describes the area in which you live?' : 'Which_of_the_following_best_describes_the_area_in_which_you_live?',
    'TH - Which region/city do you live in?': 'Region',
    'Which best applies to the home you live in?': 'best applies to the home you live in?',
    'Which one of these applies to you?': 'decision maker'
    
})

# Germany['Range_household_income'] = Germany['Range_household_income'].astype(str)

# Display all columns to identify any extra spaces or unusual characters
# for col in Germany.columns:
#     print(f"'{col}'")

Thailand.columns = Thailand.columns.str.strip() # Clean up any extra whitespace in column names
print(Thailand.columns)

Index(['Response ID', 'Date Submitted', 'Status', 'IP Address', 'Longitude',
       'Latitude', 'Country', 'City', 'State/Region', 'Postal', 'language',
       'BRID', 'BCID', 'TEST MODE (ON/OFF)', 'Termination page', 'Month',
       'Week',
       'Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.',
       'New Hidden Value', 'Copy of New Hidden Value',
       'Which country are you currently residing in?', 'Region',
       'Which_of_the_following_best_describes_the_area_in_which_you_live?',
       'Gender', 'Age', 'Age Range', 'Range_household_income',
       'highest level of education you have completed?',
       'best applies to the home you live in?', 'decision maker'],
      dtype='object')

In [106]:
# Convert the columns to string
Thailand['Gender'] = Thailand['Gender'].astype(str)
Thailand['highest level of education you have completed?'] = Thailand['highest level of education you have completed?'].astype(str)
Thailand['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Thailand['Which_of_the_following_best_describes_the_area_in_which_you_live?'].astype(str)
Thailand['Region'] = Thailand['Region'].astype(str)
Thailand['Age Range'] = Thailand['Age Range'].astype(str)
Thailand['Range_household_income'] = Thailand['Range_household_income'].astype(str)
Thailand['best applies to the home you live in?'] = Thailand['best applies to the home you live in?'].astype(str)
Thailand['decision maker'] = Thailand['decision maker'].astype(str)

# Rename specific row values

################################################## Fixed ##################################################
Thailand['Gender'] = Thailand['Gender'].replace({
    '1': 'Male',
    '2': 'Female',
    '3': 'Non-binary or gender fluid',
    '4': 'I prefer to self-identify',
    '99': 'Prefer not to answer'
})

Thailand['highest level of education you have completed?'] = Thailand['highest level of education you have completed?'].replace({
    '1': 'Primary and Secondary school',
    '2': 'Middle School / High School',
    '3': 'Diploma / Technical College / Junior College',
    '4': 'University',
    '5': 'Post graduate studies',
    '97': 'Others'
})

Thailand['Which_of_the_following_best_describes_the_area_in_which_you_live?'] = Thailand['Which_of_the_following_best_describes_the_area_in_which_you_live?'].replace({
    '1': 'Rural/ village',
    '2': 'Small Town',
    '3': 'Suburban/ city outskirts',
    '4': 'Urban city/ large town',
    '97': 'Other',
    '99': 'Prefer not to answer'
})

Thailand['best applies to the home you live in?'] = Thailand['best applies to the home you live in?'].replace({
    '1': 'I own it',
    '2': 'I rent it',
    '3': "I live in someone else's home",
    '4': 'Others'
})

Thailand['Age Range'] = Thailand['Age Range'].replace({
    '1': 'Below 18',
    '2': '18-24',
    '3': '25-34',
    '4': '35-44',
    '5': '45-60',
    '6': '61-70',
    '7': '71 and above'
})

Thailand['decision maker'] = Thailand['decision maker'].replace({
    '1': 'I am solely responsible for choosing the domestic appliances I buy',
    '2': 'I share responsibility with someone else in the household',
    '3': 'Someone else in the household is responsible for choosing the domestic appliances I buy'
})

###############################   Follow each country's requirement  ####################################
Thailand['Region'] = Thailand['Region'].replace({
    '1': 'Bangkok',
    '2': 'Northern Thailand',
    '3': 'Northeastern Thailand',
    '4': 'Central Thailand',
    '97': 'Others'
})

# Define income range replacements for "Bangkok" and other regions
income_ranges_bangkok = {
    '1': 'Less than THB 10,000',
    '2': 'Less than THB 15,000',
    '3': 'THB 10,000 - 15,000',
    '4': 'THB 15,001 - 30,000',
    '5': 'THB 30,001 - 50,000',
    '6': 'THB 50,001 - 100,000',
    '7': 'Above THB 50,000',
    '8': 'Above THB 100,001',
    '99': 'Do not wish to answer/Don’t know'
}

# Define income range for other regions
income_ranges_other = {
    '1': 'Less than THB 10,000',
    '2': 'THB 10,000 - 15,000',
    '3': 'THB 15,001 - 30,000',
    '4': 'THB 30,001 - 50,000',
    '5': 'Above THB 50,000',
    '99': 'Do not wish to answer/Don’t know'
}

# Apply the income range replacement based on the region
Thailand['Range_household_income'] = Thailand.apply(
    lambda row: income_ranges_bangkok.get(row['Range_household_income']) if row['Region'] == 'Bangkok' 
                else income_ranges_other.get(row['Range_household_income']), 
    axis=1
)

print(Thailand[['Region', 'Range_household_income']].head())

             Region Range_household_income
0  Central Thailand       Above THB 50,000
1  Central Thailand    THB 30,001 - 50,000
2           Bangkok   THB 50,001 - 100,000
3           Bangkok    THB 30,001 - 50,000
4           Bangkok    THB 15,001 - 30,000

In [107]:
Thailand.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78252,25/11/2024 17:34:49,Complete,49.237.13.91,100.500298,13.6855,Thailand,Bangkok,40.0,10140.0,...,7,Central Thailand,Suburban/ city outskirts,Male,36,35-44,"Above THB 50,000",University,I own it,I am solely responsible for choosing the domes...
1,78269,25/11/2024 17:42:59,Complete,180.180.193.142,100.191704,13.8667,Thailand,Nakhon Pathom,53.0,73000.0,...,7,Central Thailand,Urban city/ large town,Male,32,25-34,"THB 30,001 - 50,000",University,I own it,I am solely responsible for choosing the domes...

In [108]:
print(Thailand['Range_household_income'].value_counts(), "\n")
print(Thailand['Region'].value_counts())

Range_household_income
THB 30,001 - 50,000                 158
Above THB 50,000                     61
THB 15,001 - 30,000                  52
THB 50,001 - 100,000                 43
Above THB 100,001                    16
Less than THB 10,000                  7
Less than THB 15,000                  7
Do not wish to answer/Don’t know      2
Name: count, dtype: int64

Region
Bangkok                  191
Central Thailand          81
Northeastern Thailand     67
Northern Thailand         37
Others                    23
Name: count, dtype: int64

In [109]:
Thailand.head(2)

,Response ID,Date Submitted,Status,IP Address,Longitude,Latitude,Country,City,State/Region,Postal,...,Which country are you currently residing in?,Region,Which_of_the_following_best_describes_the_area_in_which_you_live?,Gender,Age,Age Range,Range_household_income,highest level of education you have completed?,best applies to the home you live in?,decision maker
0,78252,25/11/2024 17:34:49,Complete,49.237.13.91,100.500298,13.6855,Thailand,Bangkok,40.0,10140.0,...,7,Central Thailand,Suburban/ city outskirts,Male,36,35-44,"Above THB 50,000",University,I own it,I am solely responsible for choosing the domes...
1,78269,25/11/2024 17:42:59,Complete,180.180.193.142,100.191704,13.8667,Thailand,Nakhon Pathom,53.0,73000.0,...,7,Central Thailand,Urban city/ large town,Male,32,25-34,"THB 30,001 - 50,000",University,I own it,I am solely responsible for choosing the domes...

### Concat all the files and ave them into another csv file

In [110]:
# Concatenate the melted DataFrames
combined_user_profile = pd.concat([Germany, Italy, Poland, Vietnam, UK, 
                                Switzerland, Sweden, Australia, Thailand], ignore_index=True)

# Rename specific columns
combined_user_profile = combined_user_profile.rename(columns={
    'decision maker': 'Decision maker'    
})

# combined_user_profile.dropna(subset=['Response ID'], inplace=True)

# combined_user_profile.to_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\PROCESSED-DATA\SEPTEMBER\combined_user_profile.xlsx', float_format='%.0f', index=False)
# combined_user_profile.to_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\PROCESSED-DATA\OCTOBER\combined_user_profile.xlsx', float_format='%.0f', index=False)
# combined_user_profile.to_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\PROCESSED-DATA\NOVEMBER\combined_user_profile.xlsx', float_format='%.0f', index=False)
combined_user_profile.to_excel(r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\PROCESSED-DATA\DECEMBER\combined_user_profile.xlsx', float_format='%.0f', index=False)

print(combined_user_profile.head(2))

   Response ID       Date Submitted    Status     IP Address  Longitude  \
0        78230  25/11/2024 16:40:55  Complete  81.89.172.225     9.4910
1        78263  25/11/2024 17:32:48  Complete   89.247.204.9    11.5683

    Latitude  Country    City State/Region   Postal  ...  \
0  51.299301  Germany     NaN          NaN      NaN  ...
1  48.166302  Germany  Munich           02  80803.0  ...

   Which country are you currently residing in?  Region  \
0                                             2  Bayern
1                                             2  Bayern

  Which_of_the_following_best_describes_the_area_in_which_you_live?  Gender  \
0                                     Rural/ village                 Female
1                             Urban city/ large town                   Male

  Age  Age Range  Range_household_income  \
0  43      35-44     € 60.000 - € 69.999
1  28      25-34     € 50.000 - € 59.999

   highest level of education you have completed?  \
0                     Middle School / High School
1                     Middle School / High School

   best applies to the home you live in?  \
0                               I own it
1                              I rent it

                                      Decision maker
0  I am solely responsible for choosing the domes...
1  I share responsibility with someone else in th...

[2 rows x 32 columns]

In [111]:
# # Simplified path
# base_dir = r'C:\Users\aisar\OneDrive\Documents\ELECTROLUX\PROCESSED-DATA'
# month = 'OCTOBER'
# file_name = 'combined_user_profile.xlsx'

# output_path = f"{base_dir}\{month}\{file_name}"
# combined_user_profile.to_excel(output_path, float_format='%.0f', index=False)

# # Display first two rows
# print(combined_user_profile.head(2))

In [112]:
combined_user_profile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3584 entries, 0 to 3583
Data columns (total 32 columns):
 #   Column                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                --------------  -----
 0   Response ID                                                                                                                           3584 non-null   int64
 1   Date Submitted                                                                                                                        3584 non-null   object
 2   Status                                                                                                                                3584 non-null   object
 3   IP Address                                                                                                                            3584 non-null   object
 4   Longitude                                                                                                                             3583 non-null   float64
 5   Latitude                                                                                                                              3583 non-null   float64
 6   Country                                                                                                                               3583 non-null   object
 7   City                                                                                                                                  2999 non-null   object
 8   State/Region                                                                                                                          3021 non-null   object
 9   Postal                                                                                                                                2605 non-null   object
 10  language                                                                                                                              3584 non-null   int64
 11  BRID                                                                                                                                  3584 non-null   object
 12  BCID                                                                                                                                  3584 non-null   object
 13  TEST MODE (ON/OFF)                                                                                                                    3584 non-null   object
 14  Termination page                                                                                                                      3584 non-null   object
 15  Month                                                                                                                                 3584 non-null   int64
 16  Week                                                                                                                                  3584 non-null   int64
 17  Home construction or remodeling:Do you or does any member of your household work in any of these occupations? Select all that apply.  215 non-null    float64
 18  Financial Services:Do you or does any member of your household work in any of these occupations? Select all that apply.               166 non-null    float64
 19  None of these:Do you or does any member of your household work in any of these occupations? Select all that apply.                    3217 non-null   float64
 20  New Hidden Value                                                                                                                      3584 non-null   object
 21  Copy of New Hidden Value                                                                                                              3584 non-null   object
 22  Which country are you currently residing in?                                                                                          3584 non-null   int64
 23  Region                                                                                                                                3584 non-null   object
 24  Which_of_the_following_best_describes_the_area_in_which_you_live?                                                                     3584 non-null   object
 25  Gender                                                                                                                                3584 non-null   object
 26  Age                                                                                                                                   3584 non-null   int64
 27  Age Range                                                                                                                             3584 non-null   object
 28  Range_household_income                                                                                                                3531 non-null   object
 29  highest level of education you have completed?                                                                                        3584 non-null   object
 30  best applies to the home you live in?                                                                                                 3584 non-null   object
 31  Decision maker                                                                                                                        3584 non-null   object
dtypes: float64(5), int64(6), object(21)
memory usage: 896.1+ KB